AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello api
Globals:
  Function:
    Timeout: 3

Resources:
  VideoRoomFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./packages/hello
      Dockerfile: Dockerfile
    Properties:
      ImageUri: {your-aws-account-id}.dkr.ecr.{your-aws-region}.amazonaws.com/dev-hello
      PackageType: Image
      FunctionName: HelloInEngFunction
      Events:
        VideoRoom:
          Type: Api
          Properties:
            Path: /hello
            Method: get
